insert into players (gamertag) values ("JDawg");
insert into Players (gamertag) values ("idk"  );
insert into Players (gamertag) values ("alwyn");
insert into Players (gamertag) values ("FrogGranna");
insert into Players (gamertag) values ( "PDawg");
insert into Players (gamertag) values ("frodo" );
insert into Players (gamertag) values ("The Legend 27");
insert into Players (gamertag) values ("xxx_CDawg_xxx");
insert into Players (gamertag) values ("Xx_TTV_MadJack69_xX");
insert into Players (gamertag) values ("Ruark");
insert into Players (gamertag) values ("kio");
insert into Players (gamertag) values ("MIA");